import { HTMLObfuscatorStrategy } from "../../src/classes/obfuscators/HTMLObfuscatorStrategy.js";

describe("HTMLObfuscatorStrategy", () => {
  test("returns the same string for now (placeholder behavior)", () => {
    const strategy = new HTMLObfuscatorStrategy();
    const input = "<p></p><div class=\"widget\" kind=\"Repeater\" model=\"UnitOperation\" process=\"{&quot;id&quot;:1,&quot;name&quot;:&quot;Request Comment&quot;,&quot;description&quot;:&quot;Took&quot;,&quot;site&quot;:&quot;&quot;,&quot;gmp&quot;:false,&quot;scale&quot;:&quot;&quot;,&quot;referencesLinks&quot;:&quot;&quot;,&quot;techTransferEnabled&quot;:null,&quot;integrations&quot;:&quot;&quot;,&quot;currentState&quot;:&quot;Evidence&quot;,&quot;clonedFromVersionId&quot;:null,&quot;clonedFromModel&quot;:&quot;&quot;,&quot;createdByUserId&quot;:5974,&quot;createdAt&quot;:&quot;2025-09-22T05:28:24.000Z&quot;,&quot;updatedAt&quot;:&quot;2025-09-23T07:44:13.000Z&quot;,&quot;deletedAt&quot;:null,&quot;ProjectId&quot;:1,&quot;SupplierId&quot;:null,&quot;SendingId&quot;:null,&quot;LastVersionId&quot;:7,&quot;LastApprovedVersionId&quot;:null,&quot;LastVersionTransitionId&quot;:10,&quot;Supplier&quot;:null,&quot;modelName&quot;:&quot;Process&quot;,&quot;typeCode&quot;:&quot;PR&quot;,&quot;approved&quot;:false,&quot;project&quot;:{&quot;id&quot;:1,&quot;name&quot;:&quot;Magic Pound Cake&quot;,&quot;isDemo&quot;:false,&quot;RMPId&quot;:3,&quot;deletedAt&quot;:null,&quot;riskAssessmentMethod&quot;:null,&quot;productRiskAssessmentType&quot;:&quot;Preliminary Hazards Analysis (PHA)&quot;},&quot;parents&quot;:[],&quot;projectId&quot;:1,&quot;versionId&quot;:7,&quot;cacheDate&quot;:&quot;2025-09-26T16:13:09.000Z&quot;,&quot;cacheId&quot;:2892}\"><div class=\"widget-main\"><div class=\"widget-item\"><div>Type: Repeater</div></div><div class=\"widget-item\"><div>Model: Unit Operation</div></div></div><div class=\"widget-content-container\"><div class=\"widget-content\"><p>Unit operation name <span contenteditable=\"false\" class=\"qbd-output qbd-output-widget\">UnitOperation.name</span></p></div></div></div><p></p><p>This is a unit operation <span contenteditable=\"false\" class=\"qbd-output qbd-output-direct-scope-widget  never-approved\" data-record-path=\"[&quot;UO[name='April Institute']&quot;,&quot;name&quot;]\" data-record-id=\"1\" data-record-model-name=\"UnitOperation\" data-record-column-name=\"name\" data-never-approved=\"true\">April Institute</span></p>"
    const result = strategy.obfuscateString(input);
    expect(result).toBe(input);
  });
});
